######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 26 12:57:34 2022
######################################################################

#TEMPLATE = console
DEPENDPATH += . src
INCLUDEPATH += .
TARGET = $$[TARGET]
DESTDIR = $$[DESTDIR]

# Input
SOURCES += src/rfc1481.c
