######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 26 11:13:54 2022
######################################################################

TEMPLATE = app
TARGET = $$[TARGET]
DEPENDPATH += . src
INCLUDEPATH += .
DESTDIR = $$[DESTDIR]

# Input
SOURCES += src/rfc1481.c
